type: div
attribute:
  class: well
innerHTML:
  -
    type: h2
    innerHTML: rs:summary
  -
    type: div
    innerHTML: 
      -
        type: i
        innerHTML: rs:description
  -
    type: h3
    settings:
      enabled: rs:has_params
    innerHTML: Params 
  -      
    type: widget
    settings:
      enabled: rs:has_params
    data:
      plugin: wf/table
      method: render_one
      data:
        i18n: false
        rs: rs:params
  -
    type: h3
    innerHTML: Summary 
  -
    type: div
    innerHTML:
      -
        type: span
        innerHTML: rs:start
      -
        type: span
        innerHTML: ' to '
      -
        type: span
        innerHTML: rs:end
  -
    type: div
    innerHTML:
      -
        type: span
        innerHTML: 'Hours approx: '
      -
        type: span
        innerHTML: params:hours_approx
  -
    type: div
    innerHTML:
      -
        type: span
        innerHTML: 'Hours: '
      -
        type: span
        innerHTML: rs:hours
  -
    type: div
    innerHTML:
      -
        type: span
        innerHTML: 'Hours percentage: '
      -
        type: span
        innerHTML: params:hours_percentage
  -
    type: h3
    innerHTML: Time
  -
    type: table
    attribute:
      class: table
    innerHTML:
      -
        type: thead
        innerHTML:
          -
            type: tr
            innerHTML:
              -
                type: th
                innerHTML: Summary
              -
                type: th
                innerHTML: Description
              -
                type: th
                innerHTML: Date
              -
                type: th
                innerHTML: Time
              -
                type: th
                innerHTML: Minutes
              -
                type: th
                innerHTML: Hours
      -
        type: tbody
        innerHTML: time:table_tbody_tr
  
  
  
  
  
  
  
  
  
  
  
  
  
  